version: "3"

services:
    web:
        build: .
        image: tienda_online:v1.0.0
        container_name: tienda_online
        command: python manage.py runserver 0.0.0.0:8001
        volumes:
            - .:/code
        ports:
            - 8001:8001
volumes:
    .:
