# Generated by Django 3.1 on 2021-06-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-created_on'], 'verbose_name': 'noticia', 'verbose_name_plural': 'noticias'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='updated',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='updated',
            new_name='updated_on',
        ),
        migrations.AddField(
            model_name='noticia',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
