# Generated by Django 3.1 on 2021-06-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210601_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(default='DEFAULT VALUE SLUG', max_length=200, unique=True),
        ),
    ]
