# Generated by Django 3.1 on 2021-06-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_noticia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(default='DEFAULT VALUE SLUG', max_length=200, unique=True),
        ),
    ]
